### PR TITLE
Pmemcheck store merge

### PR DESCRIPTION
**Pull request by tomaszkapela**
This is an implementation of an idea on how to make pmemcheck work faster. There's still work to be done, but this should make running more tests feasible.

Refs pmem/valgrind#30
Refs pmem/valgrind#31

---

This change is [Reviewable](https://reviewable.io/reviews/pmem/valgrind/39)

### CODE REVIEW

**Comment by marcinslusarz** [comment]
Review status: 0 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

_[pmemcheck/pmc_main.c, line 33 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KKwbeW6HPJD4ZfnxL01:-KKwbeW6HPJD4ZfnxL02:166857) ([raw file](https://github.com/pmem/valgrind/blob/f0e1ba08da2d8c5db96533a77a93cea529f191a1/pmemcheck/pmc_main.c#L33)):_

> ``` C
> #include "pub_tool_machine.h"
> #include "pub_tool_debuginfo.h"
> //#include "pub_tool_debuginfo.h"
> ```

.

---

_[pmemcheck/pmc_main.c, line 460 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KKwcJRiTJf1D9Ufp0Lf:-KKwcJRiTJf1D9Ufp0Lg:-1423313135) ([raw file](https://github.com/pmem/valgrind/blob/f0e1ba08da2d8c5db96533a77a93cea529f191a1/pmemcheck/pmc_main.c#L460)):_

> ``` C
>     struct pmem_st *old_entry;
>     // remove old overlapping entries
>     while((old_entry = VG_(OSetGen_Remove)(pmem.pmem_stores, region)) != NULL)
> ```

space between while and ( please

---

_[pmemcheck/pmc_main.c, line 473 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KKwcQjIM0dt_ySuLYPq:-KKwcQjIM0dt_ySuLYPr:889225216) ([raw file](https://github.com/pmem/valgrind/blob/f0e1ba08da2d8c5db96533a77a93cea529f191a1/pmemcheck/pmc_main.c#L473)):_

> ``` C
>             continue;
>         // adjacent entry not merge'able
>         if(!is_store_mergeable(region, old_entry))
> ```

space after if

---

_[pmemcheck/pmc_main.c, line 504 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KKwce7kRHIcES3TW0lf:-KKwce7kRHIcES3TW0lg:956396949) ([raw file](https://github.com/pmem/valgrind/blob/f0e1ba08da2d8c5db96533a77a93cea529f191a1/pmemcheck/pmc_main.c#L504)):_

> ``` C
>             VG_(OSetGen_FreeNode)(pmem.pmem_stores, existing);
>             continue;
>         } else {
> ```

s/else {//

---

_[pmemcheck/tests/store_merge.c, line 25 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KKwck7HAG-C__8yFmsv:-KKwck7HAG-C__8yFmsw:1796175430) ([raw file](https://github.com/pmem/valgrind/blob/f0e1ba08da2d8c5db96533a77a93cea529f191a1/pmemcheck/tests/store_merge.c#L25)):_

> ``` C
>     uint8_t *from = (uint8_t *)src;
>     int i;
>     for(i = 0; i < size; ++i)
> ```

space after for

---

_[pmemcheck/tests/store_merge.c, line 33 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KKwcowQ_iXG3VOu5s_E:-KKwcowQ_iXG3VOu5s_F:166857) ([raw file](https://github.com/pmem/valgrind/blob/f0e1ba08da2d8c5db96533a77a93cea529f191a1/pmemcheck/tests/store_merge.c#L33)):_

> ``` C
>     uint8_t *to = (uint8_t *)dst;
>     int i;
>     for(i = 0; i < size; ++i)
> ```

.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/valgrind/39)_

**Comment by marcinslusarz** [comment]
Review status: 0 of 10 files reviewed at latest revision, 9 unresolved discussions.

---

_[pmemcheck/pmc_main.c, line 460 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KKwkI4vteEP8luDPmN6:-KKwkI4vteEP8luDPmN7:490942995) ([raw file](https://github.com/pmem/valgrind/blob/f0e1ba08da2d8c5db96533a77a93cea529f191a1/pmemcheck/pmc_main.c#L460)):_

> ``` C
>     struct pmem_st *old_entry;
>     // remove old overlapping entries
>     while((old_entry = VG_(OSetGen_Remove)(pmem.pmem_stores, region)) != NULL)
> ```

I think you are losing information here.

---

_[pmemcheck/pmc_main.c, line 467 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KKwkO8UY28pm_uXi5IH:-KKwkO8UY28pm_uXi5II:-251706311) ([raw file](https://github.com/pmem/valgrind/blob/f0e1ba08da2d8c5db96533a77a93cea529f191a1/pmemcheck/pmc_main.c#L467)):_

> ``` C
>     search_entry.addr -= 1;
>     int i = 0;
>     for (i = 0; i < 1; ++i, search_entry.addr += 2) {
> ```

This will iterate only once - what's the point of this loop then?

---

_[pmemcheck/pmc_main.c, line 495 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KKwkuMeLKoLd0m6CPzr:-KKwkuMeLKoLd0m6CPzs:169787051) ([raw file](https://github.com/pmem/valgrind/blob/f0e1ba08da2d8c5db96533a77a93cea529f191a1/pmemcheck/pmc_main.c#L495)):_

> ``` C
>     struct pmem_st *existing;
>     // remove any overlapping stores from the collection
>     while ((existing = VG_(OSetGen_Remove)(pmem.pmem_stores, store)) !=
> ```

Again, we are losing information here.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/valgrind/39)_

**Comment by tomaszkapela** [comment]
Review status: 0 of 10 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

_[pmemcheck/pmc_main.c, line 33 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KKwbeW6HPJD4ZfnxL01:-KLGgCL2QhjaaHEb7LQ2:-499146009) ([raw file](https://github.com/pmem/valgrind/blob/f0e1ba08da2d8c5db96533a77a93cea529f191a1/pmemcheck/pmc_main.c#L33)):_
<details><summary>

<i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary>



> .
> </details>
> Done.

---

_[pmemcheck/pmc_main.c, line 460 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KKwcJRiTJf1D9Ufp0Lf:-KLGgD7DagIyI6EWXp6N:-499146009) ([raw file](https://github.com/pmem/valgrind/blob/f0e1ba08da2d8c5db96533a77a93cea529f191a1/pmemcheck/pmc_main.c#L460)):_
<details><summary>

<i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary>



> space between while and ( please
> </details>
> Done.

---

_[pmemcheck/pmc_main.c, line 460 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KKwkI4vteEP8luDPmN6:-KLGgDkpnOhStpMnv44X:-499146009) ([raw file](https://github.com/pmem/valgrind/blob/f0e1ba08da2d8c5db96533a77a93cea529f191a1/pmemcheck/pmc_main.c#L460)):_
<details><summary>

<i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary>



> I think you are losing information here.
> </details>
> Done.

---

_[pmemcheck/pmc_main.c, line 467 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KKwkO8UY28pm_uXi5IH:-KLGgEGzgB8aTsbEKr7e:-499146009) ([raw file](https://github.com/pmem/valgrind/blob/f0e1ba08da2d8c5db96533a77a93cea529f191a1/pmemcheck/pmc_main.c#L467)):_
<details><summary>

<i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary>



> This will iterate only once - what's the point of this loop then?
> </details>
> Done.

---

_[pmemcheck/pmc_main.c, line 473 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KKwcQjIM0dt_ySuLYPq:-KLGgEtdqcOf08ui7G3O:-499146009) ([raw file](https://github.com/pmem/valgrind/blob/f0e1ba08da2d8c5db96533a77a93cea529f191a1/pmemcheck/pmc_main.c#L473)):_
<details><summary>

<i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary>



> space after if
> </details>
> Done.

---

_[pmemcheck/pmc_main.c, line 495 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KKwkuMeLKoLd0m6CPzr:-KLGgFVkGyGffGxcTf8u:-499146009) ([raw file](https://github.com/pmem/valgrind/blob/f0e1ba08da2d8c5db96533a77a93cea529f191a1/pmemcheck/pmc_main.c#L495)):_
<details><summary>

<i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary>



> Again, we are losing information here.
> </details>
> Done.

---

_[pmemcheck/pmc_main.c, line 504 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KKwce7kRHIcES3TW0lf:-KLGgG22duDclNiRN8qR:-499146009) ([raw file](https://github.com/pmem/valgrind/blob/f0e1ba08da2d8c5db96533a77a93cea529f191a1/pmemcheck/pmc_main.c#L504)):_
<details><summary>

<i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary>



> s/else {//
> </details>
> Done.

---

_[pmemcheck/tests/store_merge.c, line 25 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KKwck7HAG-C__8yFmsv:-KLGgGrhdXcr2XVvk_BP:-499146009) ([raw file](https://github.com/pmem/valgrind/blob/f0e1ba08da2d8c5db96533a77a93cea529f191a1/pmemcheck/tests/store_merge.c#L25)):_
<details><summary>

<i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary>



> space after for
> </details>
> Done.

---

_[pmemcheck/tests/store_merge.c, line 33 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KKwcowQ_iXG3VOu5s_E:-KLGgHPLgZX67zNpXT2O:-499146009) ([raw file](https://github.com/pmem/valgrind/blob/f0e1ba08da2d8c5db96533a77a93cea529f191a1/pmemcheck/tests/store_merge.c#L33)):_
<details><summary>

<i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary>



> .
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/valgrind/39)_

**Comment by marcinslusarz** [comment]
_[pmemcheck/pmc_main.c, line 433 [r2]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KLGh61IY6YvbMieAM5N:-KLGh61IY6YvbMieAM5O:-1679977148) ([raw file](https://github.com/pmem/valgrind/blob/b4a68de48903d67db764747a1197f5c75b356340/pmemcheck/pmc_main.c#L433)):_

> ``` C
> {
>     Bool context_eq = cmp_exe_context(lhs->context, rhs->context);
>     return context_eq && lhs->state == rhs->state;
> ```

Please compare states first and call cmp_exe_context only when states are equal.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/valgrind/39)_

**Comment by tomaszkapela** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

_[pmemcheck/pmc_main.c, line 433 [r2]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KLGh61IY6YvbMieAM5N:-KLGsOheeU8DTf9ZyklS:-499146009) ([raw file](https://github.com/pmem/valgrind/blob/b4a68de48903d67db764747a1197f5c75b356340/pmemcheck/pmc_main.c#L433)):_
<details><summary>

<i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary>



> Please compare states first and call cmp_exe_context only when states are equal.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/valgrind/39)_

**Comment by krzycz** [comment]
Reviewed 5 of 10 files at r1, 6 of 8 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[pmemcheck/pmc_main.c, line 614 [r3]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KLGu_dOCm8oPPSfHyQK:-KLGu_dOCm8oPPSfHyQL:675941093) ([raw file](https://github.com/pmem/valgrind/blob/d0610c4ce68b8444e2c0fbb2bf927f1ea2583894/pmemcheck/pmc_main.c#L614)):_

> ``` C
> {
>     struct pmem_st *existing;
>     // remove any overlapping stores from the collection
> ```

/**/

---

_[pmemcheck/tests/store_merge.c, line 53 [r3]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KLGtl6NJIWFkQmqGmq8:-KLGtl6NJIWFkQmqGmq9:1637345546) ([raw file](https://github.com/pmem/valgrind/blob/d0610c4ce68b8444e2c0fbb2bf927f1ea2583894/pmemcheck/tests/store_merge.c#L53)):_

> ``` C
> }
> 
> int main ( void )
> ```

main(void) ?

---

_[pmemcheck/tests/store_merge.c, line 58 [r3]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KLGtihV7-waI7tasNpe:-KLGtihV7-waI7tasNpf:-1352619373) ([raw file](https://github.com/pmem/valgrind/blob/d0610c4ce68b8444e2c0fbb2bf927f1ea2583894/pmemcheck/tests/store_merge.c#L58)):_

> ``` C
>     void *base = make_map_tmpfile(FILE_SIZE);
> 
>     /* will not merged */
> ```

will not be merged

---

_[pmemcheck/tests/store_split.c, line 26 [r3]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KLGtwdZscoqf8uuWSOi:-KLGtwdZscoqf8uuWSOj:-469765787) ([raw file](https://github.com/pmem/valgrind/blob/d0610c4ce68b8444e2c0fbb2bf927f1ea2583894/pmemcheck/tests/store_split.c#L26)):_

> ``` C
> }
> 
> int main ( void )
> ```

ditto

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/valgrind/39)_

**Comment by tomaszkapela** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[pmemcheck/pmc_main.c, line 614 [r3]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KLGu_dOCm8oPPSfHyQK:-KLHOO7-z3WRcMqUHRjs:-499146009) ([raw file](https://github.com/pmem/valgrind/blob/d0610c4ce68b8444e2c0fbb2bf927f1ea2583894/pmemcheck/pmc_main.c#L614)):_
<details><summary>

<i>Previously, krzycz (Krzysztof Czurylo) wrote…</i></summary>



> /**/
> </details>
> Done.

---

_[pmemcheck/tests/store_merge.c, line 53 [r3]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KLGtl6NJIWFkQmqGmq8:-KLHOVJCONWiclL262H7:-499146009) ([raw file](https://github.com/pmem/valgrind/blob/d0610c4ce68b8444e2c0fbb2bf927f1ea2583894/pmemcheck/tests/store_merge.c#L53)):_
<details><summary>

<i>Previously, krzycz (Krzysztof Czurylo) wrote…</i></summary>



> main(void) ?
> </details>
> Done.

---

_[pmemcheck/tests/store_merge.c, line 58 [r3]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KLGtihV7-waI7tasNpe:-KLHOVclnDYx9wF3WcQ6:-499146009) ([raw file](https://github.com/pmem/valgrind/blob/d0610c4ce68b8444e2c0fbb2bf927f1ea2583894/pmemcheck/tests/store_merge.c#L58)):_
<details><summary>

<i>Previously, krzycz (Krzysztof Czurylo) wrote…</i></summary>



> will not be merged
> </details>
> Done.

---

_[pmemcheck/tests/store_split.c, line 26 [r3]](https://reviewable.io:443/reviews/pmem/valgrind/39#-KLGtwdZscoqf8uuWSOi:-KLHOYw02vvRkKzxFcP6:-499146009) ([raw file](https://github.com/pmem/valgrind/blob/d0610c4ce68b8444e2c0fbb2bf927f1ea2583894/pmemcheck/tests/store_split.c#L26)):_
<details><summary>

<i>Previously, krzycz (Krzysztof Czurylo) wrote…</i></summary>



> ditto
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/valgrind/39)_

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/valgrind/39#-:-KLHSdNTO48R65yIKSB2:1417088721)_

**Pull request merged**
