### PR TITLE
pmemcheck: add EMIT_LOG support

### PR DESCRIPTION
**Pull request by wlemkows**
This change is [Reviewable](https://reviewable.io/reviews/pmem/valgrind/58)

### CODE REVIEW

**Review by marcinslusarz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/valgrind/58)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @wlemkows)

___
*[pmemcheck/pmc_main.c, line 1794 at r1](https://reviewable.io/reviews/pmem/valgrind/58#-LILz5Br3HhAvMZ2mSwm:-LILz5Br3HhAvMZ2mSwn:b4eptz2) ([raw file](https://github.com/pmem/valgrind/blob/58ded84b8730fc89e9c911a4861d7a92ceba10d6/pmemcheck/pmc_main.c#L1794)):*
> ```C
>             if (pmem.log_stores && (pmem.loggin_on || (VG_(OSetGen_Size)
>                     (pmem.loggable_regions) != 0))) {
> 			VG_(memcpy)(emit_log, (void *)arg[1], EMIT_LOG_LEN);
> ```

Does the maximum length of this string has to be hardcoded?
___
*[pmemcheck/pmc_main.c, line 1795 at r1](https://reviewable.io/reviews/pmem/valgrind/58#-LILzJgl4Jv6lkgAp_Ip:-LILzJgl4Jv6lkgAp_Iq:bcriwb8) ([raw file](https://github.com/pmem/valgrind/blob/58ded84b8730fc89e9c911a4861d7a92ceba10d6/pmemcheck/pmc_main.c#L1795)):*
> ```C
>                     (pmem.loggable_regions) != 0))) {
> 			VG_(memcpy)(emit_log, (void *)arg[1], EMIT_LOG_LEN);
> 			VG_(emit)("%s", emit_log);
> ```

I think "|%s" would make more sense.
___
*[pmemcheck/pmc_main.c, line 1796 at r1](https://reviewable.io/reviews/pmem/valgrind/58#-LILzL2W81wXhFWSSCoj:-LILzL2W81wXhFWSSCok:b8wak2y) ([raw file](https://github.com/pmem/valgrind/blob/58ded84b8730fc89e9c911a4861d7a92ceba10d6/pmemcheck/pmc_main.c#L1796)):*
> ```C
> 			VG_(memcpy)(emit_log, (void *)arg[1], EMIT_LOG_LEN);
> 			VG_(emit)("%s", emit_log);
> 		}
> ```

Indentation inconsistent with the rest of the code (last 3 lines).

**Review by wlemkows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/valgrind/58)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @marcinslusarz)

___
*[pmemcheck/pmc_main.c, line 1794 at r1](https://reviewable.io/reviews/pmem/valgrind/58#-LILz5Br3HhAvMZ2mSwm:-LIQpZkI259PUk5sTTrF:b-896fix) ([raw file](https://github.com/pmem/valgrind/blob/58ded84b8730fc89e9c911a4861d7a92ceba10d6/pmemcheck/pmc_main.c#L1794)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Does the maximum length of this string has to be hardcoded?
</blockquote></details>

Done.
___
*[pmemcheck/pmc_main.c, line 1795 at r1](https://reviewable.io/reviews/pmem/valgrind/58#-LILzJgl4Jv6lkgAp_Ip:-LIQp_7C6YNVqtQzoXEv:b-896fix) ([raw file](https://github.com/pmem/valgrind/blob/58ded84b8730fc89e9c911a4861d7a92ceba10d6/pmemcheck/pmc_main.c#L1795)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

I think "|%s" would make more sense.
</blockquote></details>

Done.
___
*[pmemcheck/pmc_main.c, line 1796 at r1](https://reviewable.io/reviews/pmem/valgrind/58#-LILzL2W81wXhFWSSCoj:-LIQlTer8DdscjGNcO2b:b-896fix) ([raw file](https://github.com/pmem/valgrind/blob/58ded84b8730fc89e9c911a4861d7a92ceba10d6/pmemcheck/pmc_main.c#L1796)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Indentation inconsistent with the rest of the code (last 3 lines).
</blockquote></details>

Done.

**Review by marcinslusarz — CHANGES_REQUESTED** [review]
Please extend "logging" test to check that this macro works.

> Reviewed 1 of 3 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/valgrind/58#-:-LIQsH6u7yN26HPAZrDB:bz5w2yw)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by wlemkows — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/pmem/valgrind/58#-:-LIe-FmX0MG2HRQapwzS:b-896fix)* status: 2 of 4 files reviewed, all discussions resolved

**Review by marcinslusarz — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/valgrind/58)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
