### PR TITLE
pmemcheck: change execution order

### PR DESCRIPTION
**Pull request by tomaszkapela**
Swap instrumentation and actual code execution.

Refs: pmem/valgrind#43 pmem/issues#455

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/valgrind/45)

### CODE REVIEW

**Comment by tomaszkapela** [comment]
1. No tests. I didn't add them, because on my brand new Ubuntu, Valgrind tests do not compile. At least not easily. This is a really simple change, but some tests for regression would be nice.
2. This patch has to be cherry-picked to all branches.

**Review by marcinslusarz — APPROVED** [review]

**Review by marcinslusarz — APPROVED** [review]
Please fix typo in the commit message.

**Comment by krzycz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/valgrind/45#-:-KkHbZq6fJgKq3SLWF2z:bnfp4nl)*

**Comment by tomaszkapela** [comment]
Done.

**Pull request merged**
