### PR TITLE
Pmemstats

### PR DESCRIPTION
**Pull request by ryspol**
Please review

[Review on Reviewable](https://reviewable.io/reviews/pmem/valgrind/34)

### CODE REVIEW

**Comment by marcinslusarz** [comment]
Changing one of the messages and adding error summary are 2 unrelated changes. Please split it into separate commits.

**Comment by krzycz** [comment]
:+1:

**Comment by marcinslusarz** [comment]
s/missleading/misleading/ in the commit message

:+1:  from me, but I think @tomaszkapela should also review these changes.

**Comment by tomaszkapela** [comment]
Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pmem/valgrind/34)_

**Pull request merged**
