### PR TITLE
pmemcheck: remove unused/deprecated LOG related macros

### PR DESCRIPTION
**Pull request by wlemkows**
Merge after: https://github.com/pmem/pmdk/pull/3145

This patch removes (no longer needed) support for  4 user requests:
VG_USERREQ__PMC_LOG_STORES
VG_USERREQ__PMC_NO_LOG_STORES
VG_USERREQ__PMC_ADD_LOG_REGION
VG_USERREQ__PMC_REMOVE_LOG_REGION

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/valgrind/60)

### CODE REVIEW

**Review by marcinslusarz — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/valgrind/60)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @wlemkows)

___
*[pmemcheck/pmc_main.c, line 1779 at r1](https://reviewable.io/reviews/pmem/valgrind/60#-LKfoS5tEIWVx-ZLNpSy:-LKfoS5tEIWVx-ZLNpSz:b-kyzm4x) ([raw file](https://github.com/pmem/valgrind/blob/860997426fd53f251b587749c30bf32f5b1f465a/pmemcheck/pmc_main.c#L1779)):*
> ```C
>         case VG_USERREQ__PMC_RESERVED4:
>         case VG_USERREQ__PMC_RESERVED5:
>         case VG_USERREQ__PMC_RESERVED6: {
> ```

Please add new reserved client requests here.

**Review by marcinslusarz — COMMENTED** [review]
> Reviewed 7 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/valgrind/60)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @wlemkows)

**Review by wlemkows — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/valgrind/60)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @marcinslusarz)

___
*[pmemcheck/pmc_main.c, line 1779 at r1](https://reviewable.io/reviews/pmem/valgrind/60#-LKfoS5tEIWVx-ZLNpSy:-LKfswUK3ui2JIkblF6w:b-896fix) ([raw file](https://github.com/pmem/valgrind/blob/860997426fd53f251b587749c30bf32f5b1f465a/pmemcheck/pmc_main.c#L1779)):*
<details><summary><i>Previously, marcinslusarz (Marcin Ślusarz) wrote…</i></summary><blockquote>

Please add new reserved client requests here.
</blockquote></details>

Done.

**Review by marcinslusarz — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/valgrind/60)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @marcinslusarz)

**Review by marcinslusarz — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/valgrind/60)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
