### PR TITLE
pmemcheck: add error summary disabling flag

### PR DESCRIPTION
**Pull request by ryspol**
Please review

---

This change is [Reviewable](https://reviewable.io/reviews/pmem/valgrind/37)

### CODE REVIEW

**Comment by krzycz** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[pmemcheck/pmc_main.c, line 3 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/37#-KFJ7CwB3CqqzE_epwhi:-KFJ7CwB3CqqzE_epwhj:-522265429) ([raw file](https://github.com/pmem/valgrind/blob/d0909f0ba41a7e6d12ac460dbfb3fc41d0ed75c9/pmemcheck/pmc_main.c#L3)):_
-2016

---

_[pmemcheck/pmc_main.c, line 1651 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/37#-KFJ6vNkDEz7R7v3v-f3:-KFJ6vNkDEz7R7v3v-f4:-84055283) ([raw file](https://github.com/pmem/valgrind/blob/d0909f0ba41a7e6d12ac460dbfb3fc41d0ed75c9/pmemcheck/pmc_main.c#L1651)):_
Missing description of the new flag.

---

_[pmemcheck/pmc_main.c, line 1686 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/37#-KFJ70XDRA44Zmy-S8v4:-KFJ70XDRA44Zmy-S8v5:-1396079520) ([raw file](https://github.com/pmem/valgrind/blob/d0909f0ba41a7e6d12ac460dbfb3fc41d0ed75c9/pmemcheck/pmc_main.c#L1686)):_
0.1b? 0.2?

---

_[pmemcheck/pmc_main.c, line 1688 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/37#-KFJ6yHPUD_IC9HJFTjW:-KFJ6yHPUD_IC9HJFTjX:-522265429) ([raw file](https://github.com/pmem/valgrind/blob/d0909f0ba41a7e6d12ac460dbfb3fc41d0ed75c9/pmemcheck/pmc_main.c#L1688)):_
-2016

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/valgrind/37)_

**Comment by ryspol** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

_[pmemcheck/pmc_main.c, line 3 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/37#-KFJ7CwB3CqqzE_epwhi:-KFJfVaW5HBunTujgCAr:-499146009) ([raw file](https://github.com/pmem/valgrind/blob/d0909f0ba41a7e6d12ac460dbfb3fc41d0ed75c9/pmemcheck/pmc_main.c#L3)):_
Done.

---

_[pmemcheck/pmc_main.c, line 1651 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/37#-KFJ6vNkDEz7R7v3v-f3:-KFJfWkWjfBWIYyCCTJK:-499146009) ([raw file](https://github.com/pmem/valgrind/blob/d0909f0ba41a7e6d12ac460dbfb3fc41d0ed75c9/pmemcheck/pmc_main.c#L1651)):_
Done.

---

_[pmemcheck/pmc_main.c, line 1686 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/37#-KFJ70XDRA44Zmy-S8v4:-KFJfXj83VBxMqPMEdp9:-499146009) ([raw file](https://github.com/pmem/valgrind/blob/d0909f0ba41a7e6d12ac460dbfb3fc41d0ed75c9/pmemcheck/pmc_main.c#L1686)):_
Done.

---

_[pmemcheck/pmc_main.c, line 1688 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/37#-KFJ6yHPUD_IC9HJFTjW:-KFJfY8etcJ8Z6EYNVYk:-499146009) ([raw file](https://github.com/pmem/valgrind/blob/d0909f0ba41a7e6d12ac460dbfb3fc41d0ed75c9/pmemcheck/pmc_main.c#L1688)):_
Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/valgrind/37)_

**Comment by marcinslusarz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

_[pmemcheck/pmc_main.c, line 1651 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/37#-KFJ6vNkDEz7R7v3v-f3:-KFJiJyByNyobKkUoDzn:-328394155) ([raw file](https://github.com/pmem/valgrind/blob/d0909f0ba41a7e6d12ac460dbfb3fc41d0ed75c9/pmemcheck/pmc_main.c#L1651)):_
"recognition" does not belong here

---

_[pmemcheck/pmc_main.c, line 1019 [r2]](https://reviewable.io:443/reviews/pmem/valgrind/37#-KFJitS0c42uYgeDVVD4:-KFJitS0c42uYgeDVVD5:2086901756) ([raw file](https://github.com/pmem/valgrind/blob/0b96ff3d875494c0212ca3a1d778649bc4f5e3b7/pmemcheck/pmc_main.c#L1019)):_
pmemcheck seems to be using spaces for indentation

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/valgrind/37)_

**Comment by tomaszkapela** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/valgrind/37)_

**Comment by ryspol** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

_[pmemcheck/pmc_main.c, line 1651 [r1]](https://reviewable.io:443/reviews/pmem/valgrind/37#-KFJ6vNkDEz7R7v3v-f3:-KFJrGNumeuRG6M-rWGk:-499146009) ([raw file](https://github.com/pmem/valgrind/blob/d0909f0ba41a7e6d12ac460dbfb3fc41d0ed75c9/pmemcheck/pmc_main.c#L1651)):_
Done.

---

_[pmemcheck/pmc_main.c, line 1019 [r2]](https://reviewable.io:443/reviews/pmem/valgrind/37#-KFJitS0c42uYgeDVVD4:-KFJrPEHsUEC7kyig3oR:-499146009) ([raw file](https://github.com/pmem/valgrind/blob/0b96ff3d875494c0212ca3a1d778649bc4f5e3b7/pmemcheck/pmc_main.c#L1019)):_
Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/valgrind/37)_

**Comment by marcinslusarz** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/valgrind/37)_

**Comment by tomaszkapela** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/valgrind/37#-:-KFJtgidaY-IMhKpCdse:1417088721)_

**Comment by tomaszkapela** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pmem/valgrind/37)_

**Pull request merged**
