### PR TITLE
pmemcheck: add "DEEP_SYNC" client request

### PR DESCRIPTION
**Pull request by marcinslusarz**
This change is [Reviewable](https://reviewable.io/reviews/pmem/valgrind/81)

### CODE REVIEW

**Review by pbalcer — APPROVED** [review]

**Review by wlemkows — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/valgrind/81#-:-M5Wg6Z76uf5rrA4q82M:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/valgrind/81#-:-M5WkaHP8r59ci6oNpnV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by krzycz** [comment]
What is DEEP_SYNC?

**Comment by pbalcer** [comment]
https://github.com/pmem/pmdk/pull/4697/files#diff-bd2d3e85b6a7e4d3c9668d014907dfac

**Comment by krzycz** [comment]
IMHO, the word "sync" is pretty confusing. AFAIR, it used to be called "deep flush" or "deep persist". We could also name it "forced flush/persist", but "sync"?

Anyway, the actual problem here is that logically DEEP_SYNC is an equivalent of explicit FLUSH+FENCE, so what's the point in having a separate opcode for that? I mean, from pmemcheck perspective, there is no difference between *pmem_persist* and *pmem_deep_persist*. Even if *libpmem* runs on a platform with eADR and *pmem_persist* is no-op, it would still emit DO_FLUSH+DO_FENCE. IOW, for pmemcheck, every "persist" is a "deep persist". We can differentiate it for the purpose of pmemcheck logs to see if "FLUSH+FENCE" originated from "regular" or "deep" persist, but how does it affect the actual pmemcheck behavior and error detection? Do we have special mode in pmemcheck that tests the code against potential ADR/eADR failure?

**Comment by pbalcer** [comment]
deep_sync name was to differentiate it from flush/persist functions. We've since decided to rename it to simply `deep_flush` for consistency with the nvm programming model. The name is going to be confusing either way.

The idea is to verify the correctness of code that relies on deep_flush for silent data corruption detection, and yes - that requires special support in pmemcheck so that it reorders stores between deep flushes and not barriers. Hence the need to differentiate between deep_flush and normal flush+fence scenarios.

**Pull request merged**
