### PR TITLE
Update to pmem-3.17

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
Please review especially my commits, the very last five of them, introduced as they are required/helpful for this branch to work properly with pmemcheck.

Travis build of my fork:
~~https://travis-ci.com/github/lukaszstolarczuk/valgrind/builds/235313305~~
https://travis-ci.com/github/lukaszstolarczuk/valgrind/builds/235394580

The most important fixes, which we require are, at least:
https://bugs.kde.org/show_bug.cgi?id=426144
https://bugs.kde.org/show_bug.cgi?id=407764

// FYI, alternatively, there's also a rebase to master: https://github.com/lukaszstolarczuk/valgrind/tree/master

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/valgrind/85)

### CODE REVIEW

**Comment by pbalcer** [comment]
I created a pmem-3.17 branch so you can rebase.

**Comment by lukaszstolarczuk** [comment]
@pbalcer, done.
Do you want to merge this PR? This way I will be a committer of all these upstream commits. Previously we've done it the other way around, I believe - while rebasing ldorau or mslusarz were only committers of "our" commits. But on the other hand, we preserve our merge commits in the log...

**Comment by pbalcer** [comment]
I don't think it matters all that much tbh. I think I'd prefer to just merge it.

**Review by pbalcer — APPROVED** [review]

**Review by wlemkows — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/valgrind/85#-:-MhE-0k13dcPqKJhBKQ1:bnfp4nl)* status: 0 of 1021 files reviewed, all discussions resolved

**Comment by lukaszstolarczuk** [comment]
this branch was testes with libpmemobj-cpp (stable-1.13) and the build contains only one failing test (which was failing previously on the upstream valgrind, as well)

https://github.com/lukaszstolarczuk/libpmemobj-cpp/runs/3339695123?check_suite_focus=true

**Comment by pbalcer** [comment]
I also tested with pmdk and it worked.

**Pull request merged**
